let
    DataInicial = #date(2020,1,1),
    DataFinal = #date(2022,12,31),
    QtdDias = Duration.Days(DataFinal-DataInicial)+1,
    ListaDatas = List.Dates(DataInicial,QtdDias,#duration(1,0,0,0)),
    #"Convertido para Tabela" = Table.FromList(ListaDatas, Splitter.SplitByNothing(), null, null, ExtraValues.Error),
    #"Tipo Alterado" = Table.TransformColumnTypes(#"Convertido para Tabela",{{"Column1", type date}}),
    #"Colunas Renomeadas" = Table.RenameColumns(#"Tipo Alterado",{{"Column1", "Data"}}),
    #"Ano Inserido" = Table.AddColumn(#"Colunas Renomeadas", "Ano", each Date.Year([Data]), Int64.Type),
    #"Mês Inserido" = Table.AddColumn(#"Ano Inserido", "Mês", each Date.Month([Data]), Int64.Type),
    #"Colunas Renomeadas1" = Table.RenameColumns(#"Mês Inserido",{{"Mês", "NumeroMês"}}),
    #"Dias inseridos no Mês" = Table.AddColumn(#"Colunas Renomeadas1", "Dias do Mês", each Date.DaysInMonth([Data]), Int64.Type),
    #"Colunas Renomeadas2" = Table.RenameColumns(#"Dias inseridos no Mês",{{"Dias do Mês", "QtdDiasMes"}}),
    #"Nome do Mês Inserido" = Table.AddColumn(#"Colunas Renomeadas2", "Nome do Mês", each Date.MonthName([Data]), type text),
    #"Colunas Renomeadas3" = Table.RenameColumns(#"Nome do Mês Inserido",{{"Nome do Mês", "NomeMes"}}),
    #"Coluna Duplicada" = Table.DuplicateColumn(#"Colunas Renomeadas3", "NomeMes", "NomeMes - Copiar"),
    #"Colocar Cada Palavra Em Maiúscula" = Table.TransformColumns(#"Coluna Duplicada",{{"NomeMes", Text.Proper, type text}, {"NomeMes - Copiar", Text.Proper, type text}}),
    #"Primeiros Caracteres Inseridos" = Table.AddColumn(#"Colocar Cada Palavra Em Maiúscula", "Primeiros caracteres", each Text.Start([#"NomeMes - Copiar"], 3), type text),
    #"Linhas Filtradas" = Table.SelectRows(#"Primeiros Caracteres Inseridos", each true),
    #"Colunas Removidas" = Table.RemoveColumns(#"Linhas Filtradas",{"NomeMes - Copiar"}),
    #"Colunas Renomeadas4" = Table.RenameColumns(#"Colunas Removidas",{{"Primeiros caracteres", "NomeMesCurto"}}),
    #"Trimestre Inserido" = Table.AddColumn(#"Colunas Renomeadas4", "Trimestre", each Date.QuarterOfYear([Data]), Int64.Type),
    #"Prefixo Adicionado" = Table.TransformColumns(#"Trimestre Inserido", {{"Trimestre", each "T" & Text.From(_, "pt-BR"), type text}}),
    #"Semana do Ano Inserida" = Table.AddColumn(#"Prefixo Adicionado", "Semana do Ano", each Date.WeekOfYear([Data]), Int64.Type),
    #"Colunas Renomeadas5" = Table.RenameColumns(#"Semana do Ano Inserida",{{"Semana do Ano", "SemanaDoAno"}}),
    #"Dia do Ano Inserido" = Table.AddColumn(#"Colunas Renomeadas5", "Dia do Ano", each Date.DayOfYear([Data]), Int64.Type),
    #"Colunas Renomeadas6" = Table.RenameColumns(#"Dia do Ano Inserido",{{"Dia do Ano", "DiaDoAno"}})
in
    #"Colunas Renomeadas6"